# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7ddf31ee66b18b379a271b5bd17517de61b4ed78bc189d5961de9264b3e568d31397dc48b518e2e5954fa74689ec71425ab01c693ff4d0d5da891fc542286dc7

test:
  secret_key_base: c818683b73763654ffc58ef2bcfb9ed9076458d2177829fed9873f4104b14d3b5fd23cbffb602e68afb15d14aaf23937222906b80d5dc5aebf067b8f88fe76eb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
